config:
  name: 27<sup>th</sup> Annual Symposium in Reproductive Science and Women's Health
  dates: May 13 - 14, 2008
  reg_start_date: May 1, 2008
  reg_stop_date:  May 13, 2008
  location: William T. Young Library, University of Kentucky
  director: Chemyong Jay Ko, Ph.D.
